include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # TODO: override the hashCode method each time you override the equals method. 
    # If you set this line to true, you will see all the parts 
    hash_and_equals: false

analyzer:
  exclude:
    - "devdoc/**"
